"""create universities, courses and ingestion_runs

Revision ID: c6dc92a30182
Revises: 
Create Date: 2026-10-03 23:10:08.433251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dc92a30182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("country IN ('UK', 'CA')", name='ck_universities_country'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universities_country'), ['country'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('subject_area', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('study_mode', sa.String(length=10), nullable=False),
    sa.Column('intakes', sa.JSON(), nullable=False),
    sa.Column('tuition_fee_international', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('ielts_min', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("currency IN ('GBP', 'CAD')", name='ck_courses_currency'),
    sa.CheckConstraint("level IN ('Foundation', 'Undergraduate', 'Masters', 'PhD')", name='ck_courses_level'),
    sa.CheckConstraint("study_mode IN ('full_time', 'part_time')", name='ck_courses_study_mode'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'slug', 'level', name='uq_courses_university_slug_level')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_subject_area'), ['subject_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_tuition_fee_international'), ['tuition_fee_international'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_tuition_fee_international'))
        batch_op.drop_index(batch_op.f('ix_courses_subject_area'))
        batch_op.drop_index(batch_op.f('ix_courses_level'))

    op.drop_table('courses')
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universities_country'))

    op.drop_table('universities')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
